### ISSUE TITLE
Peer to Peer Code Review Exercise Morning Session

### ISSUE THREAD

**Issue by drakecdv** [Ellyboi/Portfolio#2]
Great work so far! 😄 a few suggestions would be:

- Using [Font Awesome](https://fontawesome.com/) for iconography instead of loading images on the HTML structure.
- Using a single class for items that share the same properties 
- Updating naming convention to descriptive lowercase titles 📔 
- On the CSS file use `display: flex` and `justify-content` to position items instead of using float to keep responsiveness clean 👍

**Comment by devalibello** [comment]
Change some of your class naming from upper case to lower case. This is a more professional way to do it. 😄

**Comment by adel-gu** [comment]
Hi @Ellyboi 👋🏼 

Your Project is Complete 👍🏼
